"""Add per class AP

Revision ID: 365bf8ef8ae6
Revises: 9426f6db041f
Create Date: 2026-04-21 02:12:17.432067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365bf8ef8ae6'
down_revision: Union[str, Sequence[str], None] = '9426f6db041f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('per_class_ap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'per_class_ap')
    # ### end Alembic commands ###
