"""Add project_id to ModelVersion

Revision ID: 4b8712aa92dd
Revises: 378735099b9d
Create Date: 2026-04-21 00:28:44.655367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8712aa92dd'
down_revision: Union[str, Sequence[str], None] = '378735099b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('project_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'model_versions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.drop_column('model_versions', 'project_id')
    # ### end Alembic commands ###
