"""Add f1, speed, and map75 to ModelVersion

Revision ID: 9426f6db041f
Revises: 4b8712aa92dd
Create Date: 2026-04-21 00:39:27.067607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9426f6db041f'
down_revision: Union[str, Sequence[str], None] = '4b8712aa92dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('map75', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('f1', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('speed', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'speed')
    op.drop_column('model_versions', 'f1')
    op.drop_column('model_versions', 'map75')
    # ### end Alembic commands ###
