"""add class_labels table

Revision ID: a6f833d5a024
Revises: b339a358fbde
Create Date: 2026-04-06 07:10:15.867476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f833d5a024'
down_revision: Union[str, Sequence[str], None] = 'b339a358fbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotations', 'class_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'annotations', 'class_labels', ['class_id'], ['id'])
    op.add_column('class_labels', sa.Column('description', sa.String(), nullable=True))
    op.add_column('class_labels', sa.Column('color_hex', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_labels', 'color_hex')
    op.drop_column('class_labels', 'description')
    op.drop_constraint(None, 'annotations', type_='foreignkey')
    op.alter_column('annotations', 'class_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
