"""Add User model

Revision ID: aeebbaa5be36
Revises: 973bb7bae8a0
Create Date: 2026-04-07 16:46:20.183187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeebbaa5be36'
down_revision: Union[str, Sequence[str], None] = '973bb7bae8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'annotator', 'trainer', name='user_role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_foreign_key('fk_model_training_job', 'model_versions', 'training_jobs', ['training_job_id'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_model_training_job', 'model_versions', type_='foreignkey')
    op.drop_table('users')
    # ### end Alembic commands ###
